$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: default
endpoint_name: realtime-endpoint
model: azureml:vggbased_trans_zoom_rotate_tf_softmax_15epochs:2
code_configuration:
  code: 
    local_path: ../ml/inference/
  scoring_script: score.py
environment: azureml:custom-tf-24-inference:1
instance_type: Standard_DS2_v2
instance_count: 1
app_insights_enabled: true
