$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: default
endpoint_name: realtime-endpoint
model: azureml:vggbased_trans_zoom_contrast_extra_training:1
code_configuration:
  code: ../ml/inference/
  scoring_script: score_no_confidence.py
environment: azureml:custom-tf-24-inference:2
instance_type: Standard_DS2_v2
instance_count: 1
app_insights_enabled: true
request_settings:
  request_timeout_ms: 20000
