name: Model Deploy

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    paths:
      - "ml/score/**"

  # Allows this workflow to be run manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-model:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Add ML extension to Azure CLI
      uses: azure/CLI@v1
      with:
        inlinescript: |
          az extension add --name ml

    - name: Ensure endpoint exists
      uses: azure/CLI@v1
      with:
        inlinescript: |
          az ml online-endpoint create --file infra/endpoint.yml --resource-group pneumothorax-classifier --workspace-name production

    - name: Deploy model
      uses: azure/CLI@v1
      with:
        inlinescript: |
          az ml online-deployment create --file infra/model-deployment.yml --resource-group pneumothorax-classifier --workspace-name production

