name: deploy-model

on:
  push:
    branches:
      - main
    paths:
      - "ml/inference/**"
      - "infra/**/*.yml"

  # Allows this workflow to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-model:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Setup, deploy endpoint, deploy model
      uses: azure/CLI@v1
      with:
        inlinescript: |
          az extension add --name ml
          az ml online-endpoint create --file infra/endpoint.yml --resource-group pneumothorax-classifier --workspace-name production || true
          az ml online-deployment create --file infra/model-deployment.yml --resource-group pneumothorax-classifier --workspace-name production
